// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"my-go-api/controllers"
)

// Injectors from wire.go:

func InitializeEvent() (controllers.ControllerService, error) {
	engine := controllers.NewRouter()
	pingController := controllers.NewPingController(engine)
	controllerService := controllers.NewControllerService(engine, pingController)
	return controllerService, nil
}
